from pathlib import Path
import re

ROOT = Path('.')
APP = ROOT / 'app'
JAVA = APP / 'src/main/java/sa/techlight/customerdisplay'
MANIFEST = APP / 'src/main/AndroidManifest.xml'
GRADLE = APP / 'build.gradle'

stable_activity = JAVA / 'KitchenStableActivity.java'
stable_meta = JAVA / 'KitchenStableMetaStore.java'
if not stable_activity.exists() or not stable_meta.exists():
    raise SystemExit('Stable 6.8 sources are missing')

# Route the single launcher entry to the stable activity while retaining the proven
# V4.8 transport, parsers and durable queue generated by the baseline scripts.
manifest = MANIFEST.read_text(encoding='utf-8')
for permission in (
    'android.permission.RECORD_AUDIO',
    'android.permission.VIBRATE',
    'android.permission.MODIFY_AUDIO_SETTINGS',
):
    declaration = f'    <uses-permission android:name="{permission}" />\n'
    if permission not in manifest:
        marker = '    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />\n'
        if marker not in manifest:
            raise SystemExit('Manifest permission insertion point not found')
        manifest = manifest.replace(marker, marker + declaration, 1)

if 'android.hardware.microphone' not in manifest:
    feature_marker = '    <uses-feature android:name="android.hardware.touchscreen" android:required="false" />\n'
    if feature_marker not in manifest:
        raise SystemExit('Manifest feature insertion point not found')
    manifest = manifest.replace(
        feature_marker,
        feature_marker + '    <uses-feature android:name="android.hardware.microphone" android:required="false" />\n',
        1,
    )

manifest = manifest.replace('android:label="TechPro Kitchen - ضوء التقنية"',
                            'android:label="TechLight Kitchen - ضوء التقنية"')
manifest = manifest.replace('android:name=".KitchenActivityV42"',
                            'android:name=".KitchenStableActivity"', 1)
if 'android:name=".KitchenStableActivity"' not in manifest:
    raise SystemExit('Could not route manifest to KitchenStableActivity')
MANIFEST.write_text(manifest, encoding='utf-8')

# Route successful login and boot autostart to the stable screen.
login_path = JAVA / 'KitchenLoginActivityV3.java'
login = login_path.read_text(encoding='utf-8')
login = login.replace('KitchenActivityV42.class', 'KitchenStableActivity.class')
login = login.replace('case "title": return "TechPro Kitchen";',
                      'case "title": return "TechLight Kitchen";')
login = login.replace('message.setText("TechPro Kitchen\\n\\n"',
                      'message.setText("TechLight Kitchen\\n\\n"')
login = login.replace('dark = !"light".equalsIgnoreCase(settings.getString("theme", "dark"));',
                      'dark = "dark".equalsIgnoreCase(settings.getString("theme", "light"));')
login = login.replace('logo.setImageResource(R.drawable.techlight_t_logo);',
                      'logo.setImageResource(dark ? R.drawable.techlight_brand_white_transparent : R.drawable.techlight_brand_transparent);')
login = login.replace('action.setBackground(round(0xFF7432E0, 16));',
                      'action.setBackground(round(0xFF6750A4, 16));')
login = login.replace('label(t("continue"), 13, 0xFF7432E0, true)',
                      'label(t("continue"), 13, 0xFF6750A4, true)')
login = login.replace('round(selected ? 0xFF7432E0 : input, 12)',
                      'round(selected ? 0xFF6750A4 : input, 12)')
login = login.replace('selected ? 0xFF7432E0 : border',
                      'selected ? 0xFF6750A4 : border')
if 'KitchenStableActivity.class' not in login:
    raise SystemExit('Login route patch failed')
login_path.write_text(login, encoding='utf-8')

boot_path = JAVA / 'KitchenBootReceiver.java'
boot = boot_path.read_text(encoding='utf-8').replace(
    'KitchenActivityV42.class', 'KitchenStableActivity.class')
if 'KitchenStableActivity.class' not in boot:
    raise SystemExit('Boot route patch failed')
boot_path.write_text(boot, encoding='utf-8')

# Version the stable branch independently from the rejected Pro line.
gradle = GRADLE.read_text(encoding='utf-8')
gradle, code_count = re.subn(r'(?m)^\s*versionCode\s+\d+\s*$', '        versionCode 680', gradle, count=1)
gradle, name_count = re.subn(r"(?m)^\s*versionName\s+'[^']+'\s*$", "        versionName '6.8.0-stable'", gradle, count=1)
if code_count != 1 or name_count != 1:
    raise SystemExit('Gradle version patch failed')
GRADLE.write_text(gradle, encoding='utf-8')

# Build-time invariants: these fail the workflow before Gradle if a future baseline
# unexpectedly removes one of the promised operational behaviours.
activity = stable_activity.read_text(encoding='utf-8')
required_activity_markers = (
    'Temporary carts stay outside the kitchen queue.',
    'Collections.sort(visible, Comparator.comparingLong(value -> value.createdAt))',
    'KitchenStableMetaStore',
    'beepModified()',
    'beepLate()',
    'showEmployeePicker',
    'showGroupPicker',
    'KitchenVoiceParser.parse',
    'startOldest()',
    'showPerformanceReport()',
)
missing = [marker for marker in required_activity_markers if marker not in activity]
if missing:
    raise SystemExit('Stable activity invariant(s) missing: ' + ', '.join(missing))

print('TechLight Kitchen Stable 6.8 routing and version patch applied')
